apiVersion: v1
kind: Pod
metadata: 
  name: my-pod-v1 
spec:  
  containers:
    - image: nginx:latest
      name: my-container
      ports:
        - containerPort: 80
      volumeMounts: 
        - name: my-vol
          mountPath: /home/ubuntu/data
  initContainers:
    - image: nginx:latest
      name: my-container-1
      command: ["sh","-c","echo hii"]
  volumes:
    - emptyDir: {}
      name: my-vol


  
  
